[package]
name = "keydock-state"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
axum = { workspace = true }
tracing = { workspace = true }
keydock-domain = { workspace = true }
keydock-usecase = { workspace = true }
keydock-support = { workspace = true }
