[package]
name = "keydock-http"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
axum-governor = "=1.0.3"
axum = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
keydock-config = { workspace = true }
keydock-domain = { workspace = true }
keydock-state = { workspace = true }
keydock-support = { workspace = true }
keydock-usecase = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
percent-encoding = { workspace = true }
real = { version = "0.1", features = ["axum"] }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }

[dev-dependencies]
http-body-util = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true }
