[package]
name = "keydock-fjall"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bytes = { workspace = true }
fjall = { workspace = true }
keydock-domain = { workspace = true }
keydock-usecase = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
